version: 2.1

orbs:
  python: circleci/python@1.4.0
  codecov: codecov/codecov@1.1.0

jobs:
  linux36:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Load python
          command: pyenv global 3.6.8
      - run:
          name: Install dependencies
          command: pip install -r requirements.dev.txt
      - run:
          name: Run Tests
          command: pytest --cov=./ --cov-report=xml
      - codecov/upload:
          file: coverage.xml
      - store_artifacts:
          path: prof/
      - store_test_results:
          path: .
    resource_class: large
  linux37:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Load python
          command: pyenv global 3.7.9
      - run:
          name: Install dependencies
          command: pip install -r requirements.dev.txt
      - run:
          name: Run Tests
          command: pytest --cov=./ --cov-report=xml
      - codecov/upload:
          file: coverage.xml
      - store_artifacts:
          path: prof/
      - store_test_results:
          path: .
    resource_class: large
  linux38:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Load python
          command: pyenv global 3.8.3
      - run:
          name: Install dependencies
          command: pip install -r requirements.dev.txt
      - run:
          name: Run Tests
          command: pytest --cov=./ --cov-report=xml
      - codecov/upload:
          file: coverage.xml
      - store_artifacts:
          path: prof/
      - store_test_results:
          path: .
    resource_class: large
  linux39:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Install python
          command:   cd /opt/circleci/.pyenv/plugins/python-build/../.. && git pull && cd - && pyenv install 3.9.5
      - run:
          name: Load python
          command: pyenv global 3.9.5
      - run:
          name: Install dependencies
          command: pip install -r requirements.dev.txt
      - run:
          name: Run Tests
          command: pytest --cov=./ --cov-report=xml
    resource_class: large
  linters:
    executor:
      name: python/default
      tag: "3.8"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.dev.txt
      - run:
          pre-commit run --all-files
      - run:
          mypy --ignore-missing-imports --scripts-are-modules .

workflows:
  main:
    jobs:
      - linux38
      - linux39
      - linters
